### PR TITLE
it's Javadoc and Scaladoc (not JavaDoc and ScalaDoc)

### PR DESCRIPTION
**Pull request by SethTisue**
I can't take it anymore, I'm gonna crack if we don't fix this

### CODE REVIEW

**Comment by SethTisue** [comment]
is anyone using GenJavadoc as a library and not just as a tool? perhaps I'm missing something, but I don't see anything in this PR that will break anyone's build. the artifact names and so forth are the same

I guess regardless, it wouldn't hurt to go to a higher version number, like 0.12 or even (gasp!) 1.0. it is de facto 1.0 at this point, right?

**Comment by ktoso** [comment]
No just as a plugin I believe; I thought someone may refer to `object GenJavadocPlugin {` in the enablePlugins etc statements? Did I get that wrong?

**Comment by SethTisue** [comment]
> I thought someone may refer to object GenJavadocPlugin { in the enablePlugins etc statements? Did I get that wrong?

oh... yes, I suppose they miiiiiight, but normal usage doesn't involve doing so. nobody in the Scala 2.12 community build is doing so. (I grepped.)

I looked at the akka-http build and it does:

```
project/Doc.scala:import sbtunidoc.{ GenJavadocPlugin
```

so note it already the lower-case D. so another reason to do this is to bring this repo in line with sbt-unidoc which already has it the right way.

Personally, I'm still comfortable with making the change in a 0.12 version. We would just release-note it.

But I would also be comfortable going all the way to 1.0.

**Comment by ktoso** [comment]
> Personally, I'm still comfortable with making the change in a 0.12 version. We would just release-note it.

Yes this sounds good enough to me, I don't mind -- not a big issue, and we're pre 1.0 anyway

**Comment by SethTisue** [comment]
ahhhhhhhhhhhh

**Pull request merged**
