### PR TITLE
Support Scala 2.12.12

### PR DESCRIPTION
**Pull request by wangyum**
This PR makes it support Scala **2.12.12**.

Scala 2.12.12 release notes:
https://github.com/scala/scala/releases/tag/v2.12.12

### CODE REVIEW

**Comment by ignasi35** [comment]
thanks @wangyum

**Comment by raboof** [comment]
(manually verified wangyum has signed the CLA)

**Comment by raboof** [comment]
(looks like I don't have the permissions to override the cla bot not replying though)

**Comment by raboof** [comment]
(https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.12.12/0.16/ should be on its way)

**Comment by ignasi35** [comment]
> (looks like I don't have the permissions to override the cla bot not replying though, /cc @SethTisue )

I'll try close/reopen to trigger it again.

**Pull request merged**
