### PR TITLE
Scala 2.13.2 is here

### PR DESCRIPTION
**Pull request by SethTisue**
(also, support 2.13.3 nightlies)

### CODE REVIEW

**Comment by SethTisue** [comment]
@raboof can I interest you in pulling the publishing levers for 2.13.2?

**Comment by raboof** [comment]
Sonatype is not liking my signatures... giving "Failed: signature-staging, failureMessage:No public key: Key with id: (61107b0f74a6daa) was not able to be located on <a href="http://pool.sks-keyservers.net:11371/">http://pool.sks-keyservers.net:11371/</a>. Upload your public key and try the operation again." while that key is right there at http://pool.sks-keyservers.net:11371/pks/lookup?search=0x061107b0f74a6daa&op=vindex .

I'll just wait a bit, perhaps it needs time to propagate, but suspicious.

**Comment by raboof** [comment]
Hmm, sending it explicitly to the ubuntu keyservers seems to have helped (`gpg --keyserver http://keyserver.ubuntu.com:11371 --send-keys 2A5E8D8495DD653F753C4C7E061107B0F74A6DAA`) - or perhaps that was just coincidence.

Anyway, on its way to maven central!

**Comment by mushtaq** [comment]
Can we please get this released?

**Comment by raboof** [comment]
It's already there: https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.13.2/0.16/

**Comment by mushtaq** [comment]
@raboof thank you!

**Pull request merged**
