### PR TITLE
Scala 2.13.4 support

### PR DESCRIPTION
**Pull request by andreaTP**
anything else needed here?

### CODE REVIEW

**Review by SethTisue — APPROVED** [review]
LGTM... #240 was the same

**Comment by SethTisue** [comment]
@raboof can you pull the release levers?

**Comment by raboof** [comment]
I'm AFK till Sunday but can do it after that (unless somebody beats me to it :) )

**Comment by raboof** [comment]
> @raboof can you pull the release levers?

looking into it now

**Comment by raboof** [comment]
(0.16 published for 2.13.4 and tested with Akka, all seems :+1: )

**Pull request merged**
