### PR TITLE
Add support for Scala 2.12.13

### PR DESCRIPTION
**Pull request by marcospereira**
I hope this is all it needs. 😅

### CODE REVIEW

**Review by SethTisue — APPROVED** [review]

**Comment by marcospereira** [comment]
Thank you, @SethTisue. Can we have a release with 2.12.13 support? I was validating this Scala version in Lightbend Telemetry, but it depends on genjavadoc support.

**Comment by SethTisue** [comment]
the release levers in this repo are pulled by @raboof

**Comment by raboof** [comment]
I don't really want to be a bottleneck here, so it'd be good if more people could do this... but happy to take care of it again :)

**Comment by SethTisue** [comment]
@raboof no good deed goes unpunished: one day you volunteer, then before you know it it's your job :-)

does `RELEASING.md` appear up-to-date to you? if so, I could give releasing a try. shifting this responsibility from the Akka team to the Scala team makes sense, actually

**Comment by raboof** [comment]
> does RELEASING.md appear up-to-date to you?

It does, but...

```
2021-01-14 19:44:20.112+0100  info [SonatypeClient] [close] Finished successfully  - (SonatypeClient.scala:179)
2021-01-14 19:44:20.113+0100  info [SonatypeClient] Promoting staging repository [comtypesafe-2792] status:closed, profile:com.typesafe(34c112e991655) description: [sbt-sonatype] genjavadoc-plugin 0.16  - (SonatypeClient.scala:216)
...
2021-01-14 19:45:44.225+0100  info [SonatypeClient]   Evaluate: id:nx-internal-ruleset, rule:RepositoryWritePolicy  - (SonatypeClient.scala:377)
2021-01-14 19:45:44.225+0100  info [SonatypeClient] The promote stage is in progress. Waiting for 15.00 sec.  - (SonatypeClient.scala:170)
2021-01-14 19:45:59.545+0100  info [SonatypeClient]   Evaluate: RepositoryWritePolicy  - (SonatypeClient.scala:377)
2021-01-14 19:45:59.546+0100  info [SonatypeClient] The promote stage is in progress. Waiting for 15.00 sec.  - (SonatypeClient.scala:170)
2021-01-14 19:46:14.872+0100  info [SonatypeClient] The promote stage is in progress. Waiting for 15.00 sec.  - (SonatypeClient.scala:170)
2021-01-14 19:46:30.175+0100  info [SonatypeClient]     Failed: RepositoryWritePolicy, failureMessage:Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/com/typesafe/genjavadoc/genjavadoc-plugin_2.13.4/0.16/genjavadoc-plugin_2.13.4-0.16.pom'  - (SonatypeClient.scala:377)
2021-01-14 19:46:30.175+0100 error [SonatypeClient] [promote] Failed  - (SonatypeClient.scala:182)
2021-01-14 19:46:30.175+0100 error [SonatypeClient] Activity name:release, started:2021-01-14T18:45:04.054Z  - (SonatypeClient.scala:456)
2021-01-14 19:46:30.177+0100 error [Sonatype] [STAGE_FAILURE] Failed to promote the repository.  - (Sonatype.scala:405)
```

... but the artifacts do seem to have been updated in `Releases`... perhaps lets wait for them to propagate to maven central and see if they work?

**Comment by SethTisue** [comment]
looks like it's trying to publish for multiple Scala versions. not sure if it would help if I saw a more complete log that included the actual commands you issued

but yeah maybe it's fine if the ones that we already published for fail as expected, as long as the one we want succeeds

@marcospereira let us know if there's a problem (after waiting for propagation)

**Comment by marcospereira** [comment]
@raboof I think it failed because 0.16 is already there for Scala 2.13.4, so it won't override the existing release.

> 2021-01-14 19:46:30.175+0100  info [SonatypeClient]     Failed: RepositoryWritePolicy, failureMessage:Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/com/typesafe/genjavadoc/genjavadoc-plugin_2.13.4/0.16/genjavadoc-plugin_2.13.4-0.16.pom'  - (SonatypeClient.scala:377)

And https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.13.4/0.16/ shows it was released `2020-11-23 09:52`. Well, since it is published under `com/typesafe`, I have the permissions to publish it too.

Let me try and later @SethTisue can punish me too.

**Comment by marcospereira** [comment]
0.16 artifacts for Scala 2.12.13 are there now. It will just take the usual time to sync to the central repo. :-)

**Comment by SethTisue** [comment]
https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.12.13/0.16/ 🎉

**Comment by raboof** [comment]
Oops, my local sonatype-staging still had the 2.13.4 artifacts. Makes sense after all ;) #261

**Pull request merged**
