### PR TITLE
use point positions in comment index

### PR DESCRIPTION
**Pull request by lrytz**
fixes https://github.com/lightbend/genjavadoc/issues/220

i only tested this on 2.13.5 locally, let's see what travis says.

### CODE REVIEW

**Comment by lrytz** [comment]
@raboof this went green. not sure what's the best strategy for testing, i added a commit that tests everything with `-Yrangepos`. I think either the test suite should just use the compiler's default (so rangepos will be on for 2.13.4+), or everything should be tested twice (with and without rangepos).

**Review by raboof — APPROVED** [review]
I won't pretend I understand the logic/internals here, but the change looks neat, and the tests give confidence ;)

> not sure what's the best strategy for testing, i added a commit that tests everything with -Yrangepos. I think either the test suite should just use the compiler's default (so rangepos will be on for 2.13.4+), or everything should be tested twice (with and without rangepos).

TBQH I'd be fine with just testing everything with `-Yrangepos`, as that's what we're recommending going forward. If people run into trouble without it they can add `-Yrangepos` or upgrade to a newer Scala version... WDYT?

**Comment by lrytz** [comment]
In this case I'd suggest to remove the `rangepos` overrides in the tests, so that it tests the compiler's default.

**Comment by lrytz** [comment]
@raboof could you test this on Akka (2.12.13, 2.13.3, 2.13.5). Would you prefer to have a release or do your own `publishLocal`?

**Comment by lrytz** [comment]
(failure seems spurious, and travis doesn't let me restart the job, "Oh no! An error occurred. The job could not be restarted")

**Comment by raboof** [comment]
> @raboof could you test this on Akka (2.12.13, 2.13.3, 2.13.5)? Would you prefer to have a release or do your own `publishLocal`?

I'll give it a go (with `publishLocal`)

**Comment by lrytz** [comment]
Thanks!

**Comment by raboof** [comment]
Tested a couple of variations:

With genjavadoc 0.16 and default settings:
* 2.12.13 and 2.13.3: ok, 2.13.5 not ok (as expected)
With genjavadoc 0.16, enabling -Yrangepos explicitly:
* 2.12.13 and 2.13.3: both not ok (as expected)

With this branch and default settings:
* 2.12.13, 2.13.3 and 2.13.5 all ok
With this branch, enabling -Yrangepos explicitly:
* 2.12.13 and 2.13.3 both ok

So all good!

**Comment by lrytz** [comment]
Thanks for testing it!

**Pull request merged**
