### PR TITLE
support Scala 2.13.10 (and 2.13.11 nightlies)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
gah. needs `productIterator` adjustment

**Comment by He-Pin** [comment]
Waiting for it: https://github.com/akka/akka/actions/runs/3226774432/jobs/5280716214

**Comment by He-Pin** [comment]
@SethTisue Hi is there any ETA about this? thanks.

**Comment by SethTisue** [comment]
I expect to get to this on Wednesday — possibly Thursday.

**Pull request merged**
