### PR TITLE
Added Support for Scala 2.12.4

### PR DESCRIPTION
**Pull request by mahendrapk**

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM

Did we have a CLA validator here before the repository move btw @2m ? I can't remember hm

**Comment by 2m** [comment]
I think we did: https://github.com/lightbend/genjavadoc/pull/54#issuecomment-114137014

**Comment by mahendrapk** [comment]
Verification for 2.11.7 is stuck on Travis for well over 2 hours now. Apart from that is there anything else I can help with?

**Comment by SethTisue** [comment]
I have hit restart on the one red job in the matrix. seems likely to have been some transient glitch

**Comment by ktoso** [comment]
Thanks @mahendrapk  :)

**Comment by TimMoore** [comment]
Has someone released this?

**Comment by ktoso** [comment]
Not yet.

**Comment by TimMoore** [comment]
Available now: https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.12.4/0.10/

**Pull request merged**
