### PR TITLE
Support Scala 2.12.10

### PR DESCRIPTION
**Pull request by wangyum**
This PR makes it support Scala 2.12.10.

Scala 2.12.10 release notes:
- Fix regression in large string interpolations with non-String typed splices
- Revert "Generate shallower ASTs in pattern translation"
- Fix regression in classpath when JARs have 'a.b' entries beside 'a/b'

More details:
https://github.com/scala/scala/releases/tag/v2.12.10

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @wangyum,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by wangyum** [comment]
I have signed the CLA.

**Comment by wangyum** [comment]
cc @SethTisue @dwijnand

**Comment by SethTisue** [comment]
genjavadoc releases have usually been done by @2m, but he's no longer at Lightbend

@patriknw is there somebody else on the Akka team who could take on this responsibility...?

**Comment by raboof** [comment]
@SethTisue I *think* I've done one before, happy to give it a go again.

**Comment by dongjoon-hyun** [comment]
Thank you, @wangyum , @raboof and @SethTisue !

**Comment by raboof** [comment]
looking into https://github.com/lightbend/genjavadoc/issues/193 before releasing though

**Comment by dongjoon-hyun** [comment]
Great! Thank you all!

**Pull request merged**
