### PR TITLE
Support Scala 2.12.11

### PR DESCRIPTION
**Pull request by wangyum**
This PR makes it support Scala **2.12.11**.

Scala 2.12.11 release notes:
https://github.com/scala/scala/releases/tag/v2.12.11

### CODE REVIEW

**Comment by wangyum** [comment]
cc @SethTisue

**Comment by SethTisue** [comment]
@raboof want to turn the publishing cranks? there aren't any user-visible changes on master since the `v0.15` tag, so I think back-publishing is fine here.

**Comment by raboof** [comment]
Will do

**Comment by raboof** [comment]
should be on its way to central...

**Comment by raboof** [comment]
https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.12.11/0.15/

**Pull request merged**
