### PR TITLE
Compile with 2.13.0-M4

### PR DESCRIPTION
**Pull request by lrytz**
Disabled fatal warnings to accept the deprecation warnings for
`SortedSet.to` / `.from`. The alternative would be to use `rangeTo` /
`rangeFrom` and add the scala-collections-compat dependency.

Disabled the tests when running on 2.13, as scalacheck is not yet available.

### CODE REVIEW

**Comment by lrytz** [comment]
Review by @SethTisue.

Could you also release 0.11 for M4 from this branch / after merging? I don't have sonatype credentials for the `com.typesafe` org.

**Comment by SethTisue** [comment]
> I don't have sonatype credentials for the com.typesafe org

nor do I.

@2m, could you do the review and release? (I'm technically on vacation at the moment, and then busy with Scala Days NYC.)

**Comment by SethTisue** [comment]
ScalaTest 3.0.6-SNAP1 is now available for M4, so the workaround in this PR can be removed.

**Comment by lrytz** [comment]
@2m this should be ready now

**Comment by 2m** [comment]
Artifacts are in maven central: https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.13.0-M4/0.11/

**Pull request merged**
