### PR TITLE
All traits compile to public interfaces

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by SethTisue** [comment]
I don't think scalac treats traits and classes any differently w/r/t access. Any top-level trait or class must be public in the bytecode, in order for it to be accessible by nested packages, since Scala has the nested-package concept but the JVM does not.

So I'm skeptical this can be correct.

**Comment by raboof** [comment]
I could very well have been misinterpreting things - so far I've simply been compiling test classes and looking at the resulting classes with javap. Is there anywhere I can read about such things? The Scala Language Specification doesn't seem to say anything about Java interop (which makes sense), not sure where else to look.

**Comment by raboof** [comment]
So you're saying it would be more accurate to start this logic with `if (topLevel) "public"`?

**Comment by SethTisue** [comment]
> Is there anywhere I can read about such things?

not really, sadly. see 
https://github.com/scala/docs.scala-lang/issues/1146#issuecomment-453543303

**Comment by SethTisue** [comment]
> So you're saying it would be more accurate to start this logic with if (topLevel) "public"?

there's a `!topLevel` check later, so maybe it would fall through to `public` anyway even without a second check

I don't understand what the original thinking was behind checking `m.isTrait || m.isInterface`, it seems wrong to me, but I'm not 100% confident. @adriaanm any thoughts? also maybe some digging with `git blame` would turn up some insight. in any case, if the tests pass and if any resulting diffs to the Akka docs seem correct, then that meets the prevailing quality standard in this repo, I think.

**Comment by raboof** [comment]
The `m.isTrait || m.isInterface` is likely wrong (introduced by me recently in #158), let's disregard that. So the 'original' implementation was:
```
if (m.isPublic) "public"
else if (m.isProtected && !topLevel) "protected"
else if (m.isPrivate && !topLevel) {
  if (m.isInterface || m.hasStaticFlag) "" else "private"
}
else if (strictVisibility && m.privateWithin != tpnme.EMPTY) ""
else "public" // this is the case for top level classes
```
And after this PR it becomes:
```
if (m.isPublic || m.isTrait) "public"
else if (m.isProtected && !topLevel) "protected"
else if (m.isPrivate && !topLevel) {
  if (m.isInterface || m.hasStaticFlag) "" else "private"
}
else if (strictVisibility && m.privateWithin != tpnme.EMPTY) ""
else "public" // this is the case for top level classes
```
So traits become public even when they're not toplevel, consistent with my experiment:
```
$ cat Test.scala
trait Outer {
  protected trait Inner
}
$ scalac Test.scala
$  javap Outer\$Inner
Compiled from "Test.scala"
public interface Outer$Inner {
}
```

**Pull request merged**
